### ISSUE TITLE
Cookies can only be modified in a Server Action or Route Handler

### ISSUE THREAD

**Issue by padupuy** [rwieruch/next-authentication#3]
Hi @rwieruch !

I was reading your [blog post](https://www.robinwieruch.de/next-authentication/) and wondering when this code will be executed ?  
I thought that it was forbidden to update the cookies during the rendering phase.  
This code can raise the famous error :  

> Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options

https://github.com/rwieruch/next-authentication/blob/8346197aea71b6219d9424a7aebfdcb2f0fba2f8/src/features/auth/queries/get-auth.ts#L22-L41

thank you for all your articles, they are great resources 🫶

**Comment by rwieruch** [comment]
Hi @padupuy good point. I had the same question and you'll find the answer over here: https://github.com/lucia-auth/lucia/discussions/1540#discussioncomment-9167350 I hope this helps!

**Comment by padupuy** [comment]
Maybe a better way to handle the refresh token flow would be to use the middleware to check the validity of the session ?   
If the session is expired, try to renew it :  
- If it succeeded, set the new cookies
- If it failed, logout the user. 

I'm also closely following the status of the Next.js RFC "Request Interceptors" https://github.com/vercel/next.js/pull/70961
